In [3]:
import pandas as pd
import numpy as np
import os
import cv2

In [4]:
fakeDF=pd.read_csv("fakeFrame.csv")
realDF=pd.read_csv("realFrame.csv")

In [5]:
realDF.head()

   Folder  FrameCount         File Path  Label
0       0          32  real/frames/0000      1
1       1          32  real/frames/0001      1
2       2          32  real/frames/0002      1
3       3          32  real/frames/0003      1
4       4          32  real/frames/0004      1

In [6]:
fakeDF.head()

      Folder  FrameCount              File Path  Label
0  0000_fake          32  fake/frames/0000_fake      0
1  0001_fake          32  fake/frames/0001_fake      0
2  0002_fake          32  fake/frames/0002_fake      0
3  0003_fake          32  fake/frames/0003_fake      0
4  0004_fake          32  fake/frames/0004_fake      0

In [7]:
df=pd.concat([fakeDF,realDF],ignore_index=True)

In [15]:
def extractFrames(path,output_folder):
    os.makedirs(output_folder,exist_ok=True)

    cap = cv2.VideoCapture(path)

    if not cap.isOpened():
        print("Wrong Path",path)
        return
    frameCount=0
    while True:
        ret,frame=cap.read()

        if not ret:
            break

        frame_path=os.path.join(output_folder,f"frame_{frameCount}.jpg")

        cv2.imwrite(frame_path,frame)

        frameCount+=1
        
    cap.release()

In [9]:
def extractSpecificFrames(path, output_folder, num_frames):
    os.makedirs(output_folder, exist_ok=True)

    cap = cv2.VideoCapture(path)


    if not cap.isOpened():
        print("Error opening video:", path)
        return
    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    step = total_frames // num_frames

    frame_id = 0
    saved = 0

    while saved < num_frames:
        cap.set(cv2.CAP_PROP_POS_FRAMES, frame_id)

        ret, frame = cap.read()
        if not ret:
            break

        frame_path = os.path.join(output_folder, f"frame_{saved}.jpg")
        
        cv2.imwrite(frame_path, frame)

        saved += 1
        frame_id += step

    cap.release()

In [10]:
# folders=df['File Path']

# for folder in folders:
#     if folder == "fake/frames/0004_fake" or folder == "real/frames/0004":
#         continue
#     f=folder.split("/")
#     f.pop(1)
#     folder="/".join(f)
#     if 'fake' in folder:
#         extractSpecificFrames(f"{folder}.mp4",f"dataset/64/fake/{f[1]}",64)
#     else:
#         extractSpecificFrames(f"{folder}.mp4",f"dataset/64/real/{f[1]}",64)

In [17]:
folders=df["File Path"]
for folder in folders:
    if folder == "fake/frames/0004_fake" or folder == "real/frames/0004":
        continue
    f=folder.split("/")
    f.pop(1)
    folder="/".join(f)
    if 'fake' in folder:
        extractFrames(f"{folder}.mp4",f"dataset/full/fake/{f[1]}")
    else:
        extractFrames(f"{folder}.mp4",f"dataset/full/real/{f[1]}")

In [ ]:
# extractSpecificFrames("fake/0004_fake.mp4","test_dataset/fake/32/0004_fake",32)
# extractSpecificFrames("real/0004.mp4","test_dataset/real/32/0004",32)

TypeError: extractFrames() takes 2 positional arguments but 3 were given